% testPEEL.m

TNUAGE=200*rand(1000,3)-100;
[TPOINTS,TSEGMENTS,TFACES]=skin(TNUAGE,2);
drawskin(TPOINTS,TSEGMENTS,TFACES,TNUAGE);
PEEL_CLOUD=PEEL(TPOINTS,TSEGMENTS,TNUAGE);
drawskin(TPOINTS,TSEGMENTS,TFACES,PEEL_CLOUD);